"""empty message

Revision ID: 64947173427b
Revises: a0fb34cb9915
Create Date: 2024-10-18 13:21:41.962759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64947173427b'
down_revision = 'a0fb34cb9915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('uri')

    # ### end Alembic commands ###
