"""empty message

Revision ID: a0fb34cb9915
Revises: dc56057e51ce
Create Date: 2024-10-16 10:19:00.372260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0fb34cb9915'
down_revision = 'dc56057e51ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfakey', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mfaenabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfaenabled')
        batch_op.drop_column('mfakey')

    # ### end Alembic commands ###
