"""empty message

Revision ID: bc67b5d1c4af
Revises: 64947173427b
Create Date: 2024-10-18 13:24:46.986009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc67b5d1c4af'
down_revision = '64947173427b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('uri')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
